#### 낚시 게임 : 제주도 가장 ~ 낚자 낚어 프로그래밍

In [1]:
import time 
import random 
import pandas as pd 
import numpy as np 

1. 낚시터 구현하기 

In [2]:
pd.read_excel('물고기표.xlsx')

No1  No2     물고기      가격
0    2.0  6.0  가는꼬리쥐치  1631.0
1    1.0  4.0    가다랑어  2917.0
2    3.0  5.0     가라지  1203.0
3    3.0  4.0   가면놀래기  1751.0
4    1.0  4.0     가숭어  4483.0
..   ...  ...     ...     ...
746  2.0  4.0  흰배환도상어  2116.0
747  2.0  4.0    흰붕장어  7953.0
748  1.0  3.0   흰점꺼끌복  6207.0
749  2.0  4.0    히메성대  9362.0
750  3.0  6.0     히메치  1074.0

[751 rows x 4 columns]

In [3]:
def game_fishing_center(): 
    print('자자자 ~ 신중하게 낚시를 시작합니다....')
    
    fishing = pd.read_excel('물고기표.xlsx')
    return fishing 

print(game_fishing_center())

자자자 ~ 신중하게 낚시를 시작합니다....
     No1  No2     물고기      가격
0    2.0  6.0  가는꼬리쥐치  1631.0
1    1.0  4.0    가다랑어  2917.0
2    3.0  5.0     가라지  1203.0
3    3.0  4.0   가면놀래기  1751.0
4    1.0  4.0     가숭어  4483.0
..   ...  ...     ...     ...
746  2.0  4.0  흰배환도상어  2116.0
747  2.0  4.0    흰붕장어  7953.0
748  1.0  3.0   흰점꺼끌복  6207.0
749  2.0  4.0    히메성대  9362.0
750  3.0  6.0     히메치  1074.0

[751 rows x 4 columns]


In [4]:
def game_fishing_center(): 
    print('자자자 ~ 신중하게 낚시를 시작합니다....')
    
    fishing = pd.read_excel('물고기표.xlsx')
    choose_fish = np.array(fishing).reshape(-1,4)
    
    return choose_fish 

print(game_fishing_center())

자자자 ~ 신중하게 낚시를 시작합니다....
[[2.0 6.0 '가는꼬리쥐치' 1631.0]
 [1.0 4.0 '가다랑어' 2917.0]
 [3.0 5.0 '가라지' 1203.0]
 ...
 [1.0 3.0 '흰점꺼끌복' 6207.0]
 [2.0 4.0 '히메성대' 9362.0]
 [3.0 6.0 '히메치' 1074.0]]


In [5]:
fishing = pd.read_excel('물고기표.xlsx')

In [6]:
np.array(fishing).reshape(-1,4)

array([[2.0, 6.0, '가는꼬리쥐치', 1631.0],
       [1.0, 4.0, '가다랑어', 2917.0],
       [3.0, 5.0, '가라지', 1203.0],
       ...,
       [1.0, 3.0, '흰점꺼끌복', 6207.0],
       [2.0, 4.0, '히메성대', 9362.0],
       [3.0, 6.0, '히메치', 1074.0]], dtype=object)

In [7]:
choose_fish = np.array(fishing).reshape(-1,4)

In [9]:
# 낚시터 구현 

def game_fishing_center(): 
    print('자자자 ~ 신중하게 낚시를 시작합니다....')
    
    fishing = pd.read_excel('물고기표.xlsx')
    choose_fish = np.array(fishing).reshape(-1,4)
    choose_fish_num = random.randint(0, len(fishing)) # 0부터 fishing 전체 행까지 반복, 랜덤 추출
    choose_fish_waiting_num = random.randint(choose_fish[choose_fish_num][0], choose_fish[choose_fish_num][1])
    
    return choose_fish_waiting_num

print(game_fishing_center())

자자자 ~ 신중하게 낚시를 시작합니다....
3


In [13]:
random.randint(0, len(fishing))

59

In [11]:
 choose_fish_num = random.randint(0, len(fishing))

In [12]:
len(fishing)

751

In [14]:
choose_fish[choose_fish_num]

array([3.0, 5.0, '독가시치', 2624.0], dtype=object)

In [15]:
choose_fish[choose_fish_num][0]

3.0

In [16]:
choose_fish[choose_fish_num][1]

5.0

In [18]:
random.randint(choose_fish[choose_fish_num][0], choose_fish[choose_fish_num][1])

4

In [20]:
def game_fishing_center(): 
    print('자자자 ~ 신중하게 낚시를 시작합니다....')
    
    fishing = pd.read_excel('물고기표.xlsx')
    choose_fish = np.array(fishing).reshape(-1,4)
    choose_fish_num = random.randint(0, len(fishing)) # 0부터 fishing 전체 행까지 반복, 랜덤 추출
    choose_fish_waiting_num = random.randint(choose_fish[choose_fish_num][0],
                                             choose_fish[choose_fish_num][1])
    
    time.sleep(choose_fish_waiting_num) # 대기시간 주기
     
    print("낚시에 성공하였습니다.")
    print("[축하] {}님이 낚은 물고기는 {}입니다".format("닥터윌", choose_fish[choose_fish_num][2]))
  

print(game_fishing_center())

자자자 ~ 신중하게 낚시를 시작합니다....
낚시에 성공하였습니다.
[축하] 닥터윌님이 낚은 물고기는 민달고기입니다
None


In [21]:
choose_fish[choose_fish_num]

array([3.0, 5.0, '독가시치', 2624.0], dtype=object)

In [29]:
def game_fishing_center(df, id, pw): 
    print('자자자 ~ 신중하게 낚시를 시작합니다....')
    
    fishing = pd.read_excel('물고기표.xlsx')
    
    choose_fish = np.array(fishing).reshape(-1,4)
    choose_fish_num = random.randint(0, len(fishing)) # 0부터 fishing 전체 행까지 반복, 랜덤 추출
    choose_fish_waiting_num = random.randint(choose_fish[choose_fish_num][0], 
                                             choose_fish[choose_fish_num][1])
    
    time.sleep(choose_fish_waiting_num) # 대기시간 주기
     
    print("낚시에 성공하였습니다.")
    print("[축하] {}님이 낚은 물고기는 {}입니다".format("닥터윌", choose_fish[choose_fish_num][2]))
  

    # DB 저장 / 엑셀 저장 
    df.loc[len(df)] = [id, pw, choose_fish[choose_fish_num][2], 1, 
                       choose_fish[choose_fish_num][-1], "미판"]
    df.to_excel("텍스트게임.xlsx", sheet_name ="낚시게임", index=None)

In [30]:
# 상점 구현하기 

def game_store(df, id): 
    print("현재 판매하지 않은 물고기는 {}개 입니다.".format(len(df[(df['ID'] == id) & 
                                                  (df['현황'] == '미판')])))
    
df = pd.read_excel('텍스트게임.xlsx')
id ='drwill'

game_store(df, id)

현재 판매하지 않은 물고기는 1개 입니다.


In [31]:
# 상점 구현하기 

def game_store(df, id): 
    print("현재 판매하지 않은 물고기는 {}개 입니다.".format(len(df[(df['ID'] == id) & 
                                                  (df['현황'] == '미판')])))
    미판_index = df[ (df['ID'] == id ) & (df['현황'] == '미판')].index
    return 미판_index
    
df = pd.read_excel('텍스트게임.xlsx')
id ='drwill'

game_store(df, id)

현재 판매하지 않은 물고기는 1개 입니다.


Int64Index([74], dtype='int64')

In [37]:
# 상점 구현하기 

def game_store(df, id, pw): 
    print("현재 판매하지 않은 물고기는 {}개 입니다.".format(len(df[(df['ID'] == id) & 
                                                  (df['현황'] == '미판')])))
    미판_index = df[ (df['ID'] == id ) & (df['현황'] == '미판')].index
    
    if len(미판_index) !=0 : 
        for i in range(len(미판_index)): 
            print("{} 물고기를 판매하였습니다.".format(df[ (df['ID'] == id) & 
                                              (df['현황'] == '미판')]))
            
            # DB 저장 / 엑셀 저장 
            df.loc[미판_index[i]] = [
                 id, pw, 
                 df[ (df['ID'] == id) & (df['현황'] == '미판')]['물고기'][미판_index[i]],
                 df[ (df['ID'] == id) & (df['현황'] == '미판')]['수량'][미판_index[i]],
                 df[ (df['ID'] == id) & (df['현황'] == '미판')]['가격'][미판_index[i]],
                 "판매" ]
    else: # 빈 경우 
        print("미판한 물고기를 완판했습니다.")

df.to_excel('텍스트게임.xlsx', sheet_name = "낚시게임", index=None)    

In [38]:
df = pd.read_excel('텍스트게임.xlsx')
df.head()

ID    PW   물고기  수량    가격  현황
0  multi  1234   가물치   1  1000  판매
1  multi  1234   가물치   2  2000  판매
2  multi  1234    흑돔   1  7000  판매
3  multi  1234  가시고기   1  2000  판매
4  multi  1234   납자루   1  3000  판매

In [39]:
# 게임 플레이 및 사용자 정보 구현하기 

def game_play(id, pw): 
    
    while True: 
        
        df = pd.read_excel('텍스트게임.xlsx')
        
        돈 = df[ (df['ID'] == id) & ( df['현황'] == '판매')]['가격'].sum()
        물고기_종류 = len(np.unique( df[df['ID'] == id]['물고기']))
        잡은_물고기 = df[df['ID'] == id]['수량'].sum()
        티어 = len(df[ (df['ID'] == id) & (df['현황'] =='판매') ])
        
        if 티어 <= 10 : 
            티어 = "낚시꿈나무"
        elif 티어 >=11 and 티어 <= 20 : 
            티어 = "낚시사생팬"
        elif 티어 >=21:
            티어 = "낚시꾼"
            
        # ID, 티어, 돈, 잡은 물고기 종류, 잡은 물고기 수 
        
        print("안녕하세요, {} 님 / 티어:{} / 가지고 있는 금액:{} / 잡은 물고기 종류:{} / 잡은 물고기 수량: {}".
             format(id, 티어, 돈, 물고기_종류, 잡은_물고기))
        
        선택 = int(input("낚시하기(1) / 상점이용(2) / 게임종료(3)"))
        
        if 선택 == 1: # 낚시터
            game_fishing_center(df, id, pw)
        elif 선택 ==2 : # 상점 
            game_store( df, id, pw)
        elif 선택 ==3 : # 게임 종료 
            break 
        

In [ ]:
# 계정 정보 생성

계정정보 = []

df = pd.read_excel('텍스트게임.xlsx')

계정 = int(input('로그인(1) / 회원가입(2)')) 

if 계정 == 1: # 로그인 
    계정정보.append(input('ID 입력: '))
    계정정보.append(int(input("PW 입력: ")))
    
    if 계정정보[0] in df['ID'].unique() and 계정정보[1] in df['PW'].unique():
        print('커먼~ 게임을 시작합니다. 유후~')
        game_play( 계정정보[0], 계정정보[1]) 
    else: 
        print( "ID 또는 PW 가 없네요~")
        pass

elif 계정 == 2: # 회원가입
    계정정보.append(input('ID 입력: '))
    계정정보.append(int(input("PW 입력: ")))
    
    print("[축하] 회원가입 완료~ ")
    print("게임을 시작합니다.")
    game_play( 계정정보[0], 계정정보[1])    

로그인(1) / 회원가입(2)1
ID 입력: multi
PW 입력: 1234
커먼~ 게임을 시작합니다. 유후~
안녕하세요, multi 님 / 티어:낚시꾼 / 가지고 있는 금액:119747 / 잡은 물고기 종류:23 / 잡은 물고기 수량: 33
낚시하기(1) / 상점이용(2) / 게임종료(3)2
현재 판매하지 않은 물고기는 8개 입니다.
       ID    PW    물고기  수량    가격  현황
24  multi  1234  노랑가오리   1  2108  미판
38  multi  1234   갈점바리   1  2651  미판
39  multi  1234  두동갈구자   1  1027  미판
40  multi  1234    잿방어   1  5080  미판
41  multi  1234   진홍퉁돔   1  7351  미판
42  multi  1234  은빛하스돔   1  8121  미판
43  multi  1234   갈고등어   1  3393  미판
44  multi  1234   홍투라치   1  5529  미판 물고기를 판매하였습니다.
       ID    PW    물고기  수량    가격  현황
38  multi  1234   갈점바리   1  2651  미판
39  multi  1234  두동갈구자   1  1027  미판
40  multi  1234    잿방어   1  5080  미판
41  multi  1234   진홍퉁돔   1  7351  미판
42  multi  1234  은빛하스돔   1  8121  미판
43  multi  1234   갈고등어   1  3393  미판
44  multi  1234   홍투라치   1  5529  미판 물고기를 판매하였습니다.
       ID    PW    물고기  수량    가격  현황
39  multi  1234  두동갈구자   1  1027  미판
40  multi  1234    잿방어   1  5080  미판
41  multi  1234   진홍퉁돔   1  7351  미판
42  mu