자료구조 

1. 리스트(기본구조) [1,2]
2. 튜플(상수, 불변) (1,2)
3. 딕셔너리(key:value)  <<- web에서는 json 형태 {1: '양진욱', 2:'노도영', 3:'송상민'}
4. 세트(set) : 집합 set()
5. 배열(numpy) array
6. 판다스 구조(Series, DataFrame) 

In [1]:
# 넘파이 
# 배열(array) 생성, 연산

# 배열(array) : 하나의 데이터 타입 허용(int, float), 다차원 구조 

import numpy as np 

np.array([1,2,3]) # 1차원 배열 

array([1, 2, 3])

In [2]:
[1,2,3]  # cf. 리스트 

[1, 2, 3]

In [3]:
np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
# 2차원 배열(수리적 모형: 행, 열)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
# 3차원 배열 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [6]:
np.arange(1,26) # 인자가 25개 있네요 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [7]:
# reshape() : 재형성해주는 함수 

np.arange(1,26).reshape(5,5)  # 1차원 >> 2차원 변환 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
# np.arange(1,26).reshape(5,4)
# ValueError: cannot reshape array of size 25 into shape (5,4)

In [9]:
np.arange(1,26).reshape(5,-1) 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
# np.arange(1,23).reshape(5,-1) 
# 전체 원소의 갯수가 맞아야 함

In [11]:
a1 = np.arange(1,26)
a1, type(a1)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25]), numpy.ndarray)

In [12]:
# 색인(indexing)
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a2[1,:]

array([4, 5, 6])

In [14]:
# 정수색인(두번째 열 선택: 차원 축소 발생)

a2[:,1]

array([2, 5, 8])

In [15]:
# 슬라이스 색인(두번째 열 선택: 차원 축소 발생 안함)
a2[:,1:2]

array([[2],
       [5],
       [8]])

In [16]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# a2에서 1, 3 행 선택 

a2[0:3:2,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [18]:
a2[[0,2],:]

array([[1, 2, 3],
       [7, 8, 9]])

In [19]:
a2[0:3:2]

array([[1, 2, 3],
       [7, 8, 9]])

In [20]:
# a2에서 1, 3 열 선택 
a2[:, [0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [21]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a2[1,1]

5

In [23]:
a2[[1,2],[1,2]] # 포인트 인덱싱

array([5, 9])

In [24]:
a2[1,1], a2[2,2]
# 2개의 포인트(점) 출력 
# 색인 함수(ix_()) 사용하여 해결 

(5, 9)

In [25]:
a2[np.ix_([1,2],[1,2])]

array([[5, 6],
       [8, 9]])

In [26]:
np.ix_?

In [27]:
# 조건 색인
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a2 > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [29]:
a2[a2>5]
# True 만 출력 

array([6, 7, 8, 9])

In [30]:
a2[:,0]>5
# 첫번째 컬럼 가져와서 5보다 큰 데이터만 출력 

array([False, False,  True])

In [31]:
a2[a2[:,0]>5,:]
# 조건의 결과를 행 방향에서 색인 값으로 전달 

array([[7, 8, 9]])

In [32]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a2[1:2,-2:-1]

array([[5]])

In [34]:
a2[a2[:,0]>5,:] 

array([[7, 8, 9]])

In [35]:
a2[a2[:,0]>5] 

array([[7, 8, 9]])

In [36]:
# 메소드

# dir(a2)
print(a2)
print(a2.dtype) # numpy 구성 데이터 타입

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64


In [37]:
a2.shape # numpy 모형(shape)

(3, 3)

In [38]:
print(a2.shape[0]) # numpy 행의 수 
print(a2.shape[1]) # numpy 열의 수

3
3


In [39]:
a2.reshape(1,9) # array 모양 변경

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [40]:
a2.ndim # ndim (number of dimension) 차원 수 

2

In [41]:
# 4. 연산 
[1,2,3] + [4,5,6] 
# list 는 서로 원소끼리 연산 불가(확장)

[1, 2, 3, 4, 5, 6]

In [42]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [43]:
# np.array([1,2,3]) + np.array([4,5,6,7])
# 서로 사이즈가 같은 배열끼리만 연산 가능

In [44]:
# 5. 형(데이터 타입) 변환 메소드 

a2.astype('float') # 실수

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [45]:
a2.astype('str')

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U21')

In [46]:
# np.where 함수 
# if 문 축약형
# SQL 형태 가져온 것임 
# SELECT ~ FROM * WHERE 조건문 
# np.where(조건, 참인 값 반환, 거짓인 값 반환)

a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.where(a2>5, 'A','B')

array([['B', 'B', 'B'],
       ['B', 'B', 'A'],
       ['A', 'A', 'A']], dtype='<U1')

In [48]:
# 7. 산술 연산 메소드 
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a2.sum() # 전체 합

45

In [50]:
a2.mean() # 전체 평균

5.0

In [51]:
a2.var() # 전체 분산

6.666666666666667

In [52]:
a2.std() # 전체 표준편차(평균에서 떨어진 정도)
# std : standard deviation

2.581988897471611

In [53]:
print(a2.min()) # 전체 최소값

print(a2.max()) # 전체 최대값

1
9


In [54]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
a2 > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [56]:
(a2 > 5).sum()
# a2에서 5보다 큰 값의 수 
# True(=1) 

4

In [57]:
(a2 > 5).any()
# True >> a2에서 5보다 큰 값이 하나라도 있을 경우 참 

True

In [58]:
(a2 > 5).all()
# False >> a2에서 모두 5보다 클 경우만 참 

False

In [59]:
a2.sum(axis=0) 
# axis(축)=0 행 기준, 행 별 총합 
# 서로 다른 행끼리, 세로방향 연산 

array([12, 15, 18])

In [60]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a2.sum(axis=1) 
# axis(축)=1 열 기준, 열 별 총합 
# 서로 다른 열끼리, 가로방향 연산 

array([ 6, 15, 24])

- [축번호]
- 2차원 : 행(0), 열(1)
- 3차원 : 층(0), 행(1), 열(2)

In [62]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a2[0:3:2,:] 

array([[1, 2, 3],
       [7, 8, 9]])

8. 전치 메소드 

In [64]:
# 1) T : 행과 열을 전치
np.arange(1,9) 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
a1 = np.arange(1,9) # 1차원 
a2 = a1.reshape(4,2) # 2차원 
print(a1)
print(a2)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [69]:
print(a1.T) # 1차원 >> 그대로 나옴 
print(a2.T) # 2차원 >> 행과 열이 바뀜 

[1 2 3 4 5 6 7 8]
[[1 3 5 7]
 [2 4 6 8]]


In [74]:
a2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [75]:
# 2) swapaxes : 두 축을 받아서 두 축을 서로 전치
# 전달 순서는 중요하지 않아요 

a2.swapaxes(0,1)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [76]:
a2.swapaxes(1,0)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [78]:
# 3) transpose (전치)
# 원본의 차원에 맞는 축 번호를 인수에 차례대로 전달. 
# 그리고 그대로 전치함. (전달되는 순서 중요)

a2.transpose(0,1) # 원본 그대로 출력

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [79]:
a2.transpose(1,0) # 행과 열 전치 

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [80]:
!pwd

/content


In [81]:
# 외부 파일 입출력 
# /content/file1.txt : Colab >> 상대경로
# C:/Users/student/Desktop/code/bigDataAnalytics : PC >> 절대경로

# 1) 파일 불러오기 
#  np.loadtxt(fname, # 파일명
            # dtype, # 데이터타입
            # delimiter, # 필드 구분기호(구분자)
            # skiprows,  # skip 할 행의 수 
            # usecols,   # 선택할 컬럼 값(위치)
            # encoding)  # 인코딩 옵션

import numpy as np 
np.loadtxt('/content/file1.txt', delimiter=',', dtype='str')

array([['stu_id', ' name', ' heigh', ' weight', ' age'],
       ['01', ' drwill', ' 177', ' 68', ' 25'],
       ['02', ' multi', ' 180', ' 70', ' 30   ']], dtype='<U7')

In [ ]:
# 2) 파일 내려쓰기 

# np.savetxt(fname,     # 파일명
#            X,         # 객체명
#            delimiter, # 구분자
#            fmt,       # 출력형식(format)
#            header,    # 헤더 출력 여부 (file  첫 문자열)
#            encoding)  # 인코딩 옵션 

In [82]:
X = np.arange(0.0,5.0,1.0)
np.savetxt('./text1.txt', X, delimiter=',', fmt='%s')

In [83]:
# [참고 : fmt 전달/변경 방식]
# %s : 문자열 
# %f : 실수(float)
# %d : 정수 

In [84]:
'%s'%123

'123'

In [85]:
'%f'%123

'123.000000'

In [86]:
'%.2f'%123

'123.00'

In [87]:
'%d'%123

'123'

In [88]:
'%7d'%123

'    123'