### 고유값과 고유 벡터

In [1]:
import numpy as np 

In [2]:
# 2차원 행렬 A 
# np.linalg.eig(a) : 고유값, 고유벡터 도출 함수 

a = np.array([[5,-1],[-2,1]]) # A 는 정방행렬이여야 함 \
a

array([[ 5, -1],
       [-2,  1]])

In [3]:
np.linalg.eig(a)

(array([5.44948974, 0.55051026]),
 array([[ 0.91209559,  0.21927526],
        [-0.40997761,  0.97566304]]))

In [4]:
w, v = np.linalg.eig(a)

In [5]:
print(w)
print()
print(v)

[5.44948974 0.55051026]

[[ 0.91209559  0.21927526]
 [-0.40997761  0.97566304]]
