In [2]:
import nltk

In [16]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [6]:
import numpy as np 
import pandas as pd
from nltk.corpus import stopwords  
import string 
import nltk 

# corpus : 말뭉치 
# stopwords : 불용어 


In [9]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [7]:
pd.read_csv('spam.csv')

Unnamed: 0  num label                    text  label_num
0           0    1  spam       your free lottery          1
1           1    2  spam  free lottery free you           1
2           2    3   ham        your free apple           0
3           3    4   ham     free to contact me           0
4           4    5   ham             I won award          0
5           5    6  spam      my lottery ticket           1

In [8]:
df = pd.read_csv('spam.csv')

In [11]:
def process_text(text):
    # text 에서 구두점(punctuation) 삭제 
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    # text 에서 불용어(접미사, 조사 등) 삭제 
    cleaned_words = [word for word in nopunc.split() 
    if word.lower() not in stopwords.words('english')]
    
    return cleaned_words

In [12]:
df

Unnamed: 0  num label                    text  label_num
0           0    1  spam       your free lottery          1
1           1    2  spam  free lottery free you           1
2           2    3   ham        your free apple           0
3           3    4   ham     free to contact me           0
4           4    5   ham             I won award          0
5           5    6  spam      my lottery ticket           1

In [13]:
df['text']

0         your free lottery
1    free lottery free you 
2          your free apple 
3       free to contact me 
4               I won award
5        my lottery ticket 
Name: text, dtype: object

In [14]:
df['text'].apply(process_text)

0          [free, lottery]
1    [free, lottery, free]
2            [free, apple]
3          [free, contact]
4                  [award]
5        [lottery, ticket]
Name: text, dtype: object

In [15]:
# text 를 토근화한 뒤, 토큰 수의 행렬 변환 

from sklearn.feature_extraction.text import CountVectorizer
message_bow = CountVectorizer(analyzer = process_text).fit_transform(df['text'])

In [21]:
# train data, test data  8:2 비율로 구분 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test \
    = train_test_split(message_bow, df['label_num'], 
                       test_size = 0.2, random_state = 42)

In [22]:
# 나이브 베이즈 모델 적용, 훈련 
# 훈련 (train) >> 모델 생성 

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train) # 훈련시, 반드시 train data 사용 

MultinomialNB()

In [32]:
# 훈련용 데이터로 예측해서 비교해 봄
classifier.predict(X_train) # 예측 값 

array([1, 0, 0, 0], dtype=int64)

In [30]:
y_train # 실제 값 

5    1
2    0
4    0
3    0
Name: label_num, dtype: int64

In [33]:
y_train.values

array([1, 0, 0, 0], dtype=int64)

In [37]:
# 학습 데이터셋에서 모델의 정확도 표현하기 

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score

In [38]:
pred = classifier.predict(X_train) # 예측 값 

In [40]:
# metrics pkg 
# - precision(정밀도), recall(재현율), f1 score(f1 스코어) 점수 구하기

print(classification_report(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         1

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [41]:
# 혼동행렬(confusion matrix)

confusion_matrix(y_train, pred)

array([[3, 0],
       [0, 1]], dtype=int64)

In [42]:
accuracy_score(y_train, pred)

1.0

In [43]:
# test data 에 적용 (모델의 성능)

classifier.predict(X_test) # 예측값

array([0, 0], dtype=int64)

In [44]:
y_test.values # 실제값

array([1, 1], dtype=int64)

In [45]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, accuracy_score

In [48]:
pred = classifier.predict(X_test)

In [49]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       2.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0



C:\Users\student\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\student\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\student\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\student\anaconda3\lib\site-packages\sklearn\metr

In [50]:
print(confusion_matrix(y_test,pred))

[[0 0]
 [2 0]]


In [52]:
accuracy_score(y_test, pred)

0.0