1. 벡터 

In [1]:
# Numpy 라이브러리 호출 
import numpy as np 

In [2]:
# 크기가 (3,) 1차원 배열 

x = np.array([1,2,3])
print(x)

[1 2 3]


In [3]:
# 크기가 (1 , 3) 2차원 배열 
u = np.array([[1,2,3]])
print(u)

[[1 2 3]]


In [4]:
# 크기가 (3, 1) 2차원 배열
v = np.array([[1],[2],[3]])
print(v)

[[1]
 [2]
 [3]]


2. 단위벡터

In [5]:
import numpy as np 
from scipy import linalg

In [6]:
s = np.array([2,3,4])
# 단위 벡터(norm) 만들기 
v_hat = s / linalg.norm(s)
print(v_hat)

[0.37139068 0.55708601 0.74278135]


In [7]:
x = np.array([1, -3])
# 단위 벡터(norm) 만들기 
v_hat = x / linalg.norm(x)
print(v_hat)

[ 0.31622777 -0.9486833 ]


In [8]:
x = np.array([-6, -8])
# 단위 벡터(norm) 만들기 
v_hat = x / (x**2).sum()**0.5
print(v_hat)

[-0.6 -0.8]


3. 제로(zeros()) 벡터 

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros(5).shape

(5,)

In [11]:
# s 변수 생성, 여기에 영 벡터을 (2,2) 배열로 만들기 

s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

4. 선형 결합

In [12]:
import numpy as np 

# a, b 변수 생성, 리스트 형태의 데이터(배열) 저장 

a = np.array([2,4])
b = np.array([1,6])
c = (4*a)+((-3)*b)
print(c)

[ 5 -2]


5. 선형 독립과 선형 종속

In [15]:
# 벡터 공간과 부분 공간 기저(basis)

# matrix_rank() >> rank 계산하기 

x1 = np.array([[2,7], [5,1]])
print(x1)
print()
print(np.linalg.matrix_rank(x1))
# rank 2개 >> 선형독립

[[2 7]
 [5 1]]

2


In [18]:
np.array([[1,2],[3,5]])

array([[1, 2],
       [3, 5]])

In [19]:
x10 = np.array([[1,2],[3,5]])
print(np.linalg.matrix_rank(x10))

2


In [16]:
np.array([[2,4],[3,6]])

array([[2, 4],
       [3, 6]])

In [17]:
x2 = np.array([[2,4],[3,6]])
np.linalg.matrix_rank(x2)
# rank 1개 >> 선형종속

1

6. 벡터의 내적과 외적 

In [20]:
# 벡터의 덧셈과 뺄셈 

x = [2,3]
y = [3,1]

# zip() 이용, 2 벡터의 1번째 원소끼리 더하고, 2번째 원소끼리 더하기 위함

[i+j for i, j in zip(x,y)]

[5, 4]

In [23]:
# zip()

print(zip([1,2,3],[4,5,6],[7,8,9]))
print()
print(list(zip([1,2,3],[4,5,6],[7,8,9])))


[(1, 4, 7), (2, 5, 8), (3, 6, 9)]


In [24]:
x = [2,3]
y = [3,1]

u = np.array(x)
v = np.array(y)

In [25]:
w = u + v
print(w)

[5 4]


In [26]:
x = [-2,-3]
y = [-3,-1]

u = np.array(x)
v = np.array(y)

In [27]:
w = u + v
print(w)

[-5 -4]


In [28]:
x = [2,3]
y = [3,1]

[i- j for i, j in zip(x,y)]

[-1, 2]

In [29]:
x = [2,3]
y = [3,1]

u = np.array(x)
v = np.array(y)

u-v

array([-1,  2])

In [30]:
# 벡터의 내적(****)

x = [3,4]
c = 8

[c*i for i in x]

[24, 32]

In [31]:
u = np.array([3,4])
c= 8

u*c

array([24, 32])

In [33]:
# 벡터의 내적
u = np.array([6,6])
v = np.array([12,0])

np.dot(u,v)
# 벡터의 내적 >>> 스칼라

72

In [34]:
# 벡터의 외적

a = (1,3,4)
b = (2,4,6)

def cross(a,b): 
    c = [a[1]*b[2] - a[2]*b[1],
         a[2]*b[0] - a[0]*b[2],
         a[0]*b[1] - a[1]*b[0]
         ]
    return c 

In [35]:
cross(a,b)

[2, 2, -2]

In [36]:
np.cross(a,b)

array([ 2,  2, -2])

7. 직교벡터

In [37]:
import numpy as np 

a = np.array([1,2])
a

array([1, 2])

In [38]:
np.linalg.norm(a) # a의 길이

2.23606797749979

In [39]:
# L1 norm 

np.linalg.norm(a, ord = 1) # a의 길이

3.0

In [40]:
# L2 norm 

np.linalg.norm(a, ord = 2) # a의 길이

2.23606797749979

In [42]:
# 유클리디언 거리 
from scipy.spatial import distance

# 두점 p1, p2 명시 

p1 = (1,2,3)
p2 = (4,5,6)

# 두점 p1, p2 간 유클리드 거리 구하기 
distance.euclidean(p1,p2)

5.196152422706632

In [45]:
# 맨하탄 거리 

from math import * 

# 두점 p1, p2 명시 

p1 = (1,2,3)
p2 = (4,5,6)

def 맨하탄거리(x,y):
     return sum(abs(a-b) for a, b in zip(x,y)) 

In [46]:
맨하탄거리(p1,p2)

9

In [48]:
# 코사인 유사도 

from numpy import dot 
import numpy as np 
from numpy.linalg import norm 

def cos_sim(a, b): 
    return dot(a,b) / (norm(a)*norm(b))

In [51]:
doc1 = np.array([1,1,1,1,0])
doc2 = np.array([1,0,1,0,1])
doc3 = np.array([2,1,1,1,1])

# 유사도 구하기 
print(cos_sim(doc1, doc2)) # 문서1, 문서2 간 코사인 유사도
print(cos_sim(doc1, doc3)) # 문서1, 문서3 간 코사인 유사도
print(cos_sim(doc2, doc3)) # 문서2, 문서3 간 코사인 유사도

# 결론 : 문서1, 문서3 간 코사인 유사도가 가장 높음 

0.5773502691896258
0.8838834764831843
0.8164965809277259
