In [1]:
# numpy library 
import numpy as np 

In [3]:
np.matrix([[1,0,0,0],[2,1,0,0],[3,0,1,0],[4,0,0,1]])

matrix([[1, 0, 0, 0],
        [2, 1, 0, 0],
        [3, 0, 1, 0],
        [4, 0, 0, 1]])

In [4]:
A = np.matrix([[1,0,0,0],[2,1,0,0],[3,0,1,0],[4,0,0,1]])
# A행렬 생성(4*4 행렬)

In [5]:
# A행렬의 역행렬을 구하시오 

np.linalg.inv(A)

matrix([[ 1.,  0.,  0.,  0.],
        [-2.,  1.,  0.,  0.],
        [-3.,  0.,  1.,  0.],
        [-4., -0., -0.,  1.]])

In [7]:
B = np.matrix([[1,2],[3,4]])
B

matrix([[1, 2],
        [3, 4]])

In [8]:
np.linalg.inv(B)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [15]:
# 전치행렬(transpose)

a = np.arange(15).reshape(3,5)
print(a)
print()
print(type(a))
print()
print(a.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

<class 'numpy.ndarray'>

(3, 5)


In [12]:
np.transpose(a)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])