## Numpy 패키지는?
선형대수를 위한 패키지
행렬,벡터

## 1. Numpy import 하기

In [1]:
# numpy라는 모듈을 별칭 np
import numpy as np

In [2]:
print(np.__version__)

1.21.6


In [3]:
# 현재 colab에 설치된 패키지들의 버전을 확인(패키지 설치치 유무)
!pip list

Package                       Version
----------------------------- ---------------------
absl-py                       1.0.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.2.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.12.0
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.4.0
audioread                     2.1.9
autograd                      1.4
Babel                         2.10.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        5.0.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.4
branca                        0.5.0
bs4                           0.0.1
Cache

In [4]:
# jupyter notebook이 아닌 리눅스 터미널에서 
# 사용하는 명령을 사용할 수 있게 만들어주는 !
# ls -> LiSt
!ls sample_data

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


## 2. ndarray 생성하기

In [9]:
# python List 생성 >> np.array() 입력, numpy ndarray 생성 
myList = [1,2,3,4]
print(type(myList))
print(myList)

<class 'list'>
[1, 2, 3, 4]


In [6]:
# python의 list와와 ndarray를 구별
arr = np.array([1,2,3,4], dtype=int)

In [7]:
arr

array([1, 2, 3, 4])

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr = np.array([1,2,3,4], dtype=float)

In [12]:
arr, type(arr)

(array([1., 2., 3., 4.]), numpy.ndarray)

### 2-1. list로 부터 생성하기

In [20]:
# 4행
mylist1 = [1, 2, 3, 4]
print(mylist1)

[1, 2, 3, 4]


In [14]:
mylist2 = [[1, 2, 3, 4], 
           [5, 6, 7, 8]]

In [19]:
arr1 = np.array(mylist1)
print(arr1)

[1 2 3 4]


In [16]:
arr2 = np.array(mylist2)

### 2-2. shape확인하기

In [17]:
arr1.shape  # 1차원

(4,)

In [21]:
arr2.shape

(2, 4)

## 3. array에서의 data 타입

array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용

In [22]:
testList=['test',1234]
testList

['test', 1234]

### 3-1. list에서의 data 타입

In [23]:
#python list
mylist = [1, 3.14, 'hello', '1234']

In [24]:
mylist

[1, 3.14, 'hello', '1234']

In [25]:
# indexing
mylist[1]

3.14

In [26]:
mylist[2]

'hello'

### 3-2. array에서의 data 타입이 혼재된 경우

### **int와 float 타입이 섞인 경우**

In [27]:
arr = np.array([1, 2, 3, 3.54])

In [28]:
arr 
# 전부 float 형태로 변경 

array([1.  , 2.  , 3.  , 3.54])

### int와 float 타입이 섞인 경우, dtype을 지정한 경우

In [29]:
myList = [1, 2, 3, 3.94]

arr = np.array(myList, dtype=int)

In [30]:
arr

array([1, 2, 3, 3])

### **int와 float와 str 타입이 혼재된 경우**

In [31]:
# int, str이 혼재된 경우 자동으로 문자열로 바꿔준다.
arr = np.array([1, 3.14, 'abc', '1234'])

In [32]:
arr

array(['1', '3.14', 'abc', '1234'], dtype='<U32')

In [33]:
arr[0] + arr[1] 
# 전부 문자로 인식

'13.14'

### int와 str 타입이 혼재된 경우, int로 dtype을 지정한 경우

In [34]:
arr = np.array([1, 3.14, '1234'], dtype=int)

In [35]:
arr

array([   1,    3, 1234])

In [37]:
# int 타입으로 명시적 형변환을 할 경우 문자가 들어간 경우 에러 발생
# arr = np.array([1, 3.14, 'abc', '1234'], dtype=int)

#ValueError 발생 >> abc를 숫자로 바꿀 수 없음

In [38]:
type(int('1234'))

int

In [39]:
import numpy as np

myArr = [1, 3.14, 3.94]
arr = np.around(myArr)
arr

array([1., 3., 4.])