In [1]:
import numpy as np

## 1. 슬라이싱 (Slicing)

배열의 부분 선택 (잘라내기)

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr.shape #1차원

(10,)

### 1-1. index 지정하여 색인

#### 1차원 array

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
len(arr)

11

In [15]:
arr[0]

0

In [16]:
arr[-11]

0

In [8]:
arr[5]

5

In [10]:
# 10번째 리스트는 없다. 따라서 out of bounds에러가 발생
# arr[10]

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# 그러나 -1은 가능, -1은 뒤에서 첫번째로 이해하자. 
arr[-1]

10

In [20]:
arr[-10]

1

In [22]:
# 뒤에서 12번째도 없다. 이것도 out of bounds에러
# arr[-12]

#### 2차원 array

In [23]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [24]:
arr2d = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [25]:
arr2d.shape

(3, 4)

arr2d[행, 열]

In [26]:
arr2d[0, 2]

3

In [27]:
arr2d[2, 1]

10

### 1-2. 범위 색인

#### 1차원

index 1**이상** 끝까지

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# index 5부터 (끝까지)
# 시작숫자:끝숫자
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

index 5 **미만** 까지

In [30]:
# 처음부터:index 5미만
arr[:5]

array([0, 1, 2, 3, 4])

index 1이상 5미만

In [31]:
arr[1:5]

array([1, 2, 3, 4])

In [32]:
#처음부터 마지막전까지(마지막미포함)
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 2차원

In [34]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [35]:
arr2d[0,:]  # 0행의 열 다 가져와

array([1, 2, 3, 4])

In [38]:
arr2d[0,:].shape

# 1행 4열 데이터를 slicing 해서 4행 데이터로 변경 

(4,)

In [39]:
arr2d[:, 2]

array([ 3,  7, 11])

부분 적으로 가져오려는 경우

In [40]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

## 2. Fancy 인덱싱

fancy 인덱싱은 범위가 아닌 **특정 index의 집합의 값을 선택하여 추출**하고 싶을 때 활용합니다.

In [42]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

반드시 **[추출하고 싶은 인덱스]** 꺾쇠 괄호로 묶어 주세요

In [43]:
idx = [1, 3, 5]

In [44]:
arr[idx]

array([23,  7, 65])

변수에 지정 후 추출도 가능합니다.

In [45]:
idx = [1, 3, 5]

In [46]:
arr[idx]

array([23,  7, 65])

### 2-2. 2차원 array

In [47]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [48]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
arr2d[[0, 2], :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [50]:
arr2d[:, [1, 2, 3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

## 3. Boolean 인덱싱

조건 필터링을 통하여 Boolean 값을 이용한 색인

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [52]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

### 3-1. True와 False 값으로 색인하기

In [53]:
myTrueFalse = [True, False, True]

In [54]:
# arr의 갯수는 
arr[myTrueFalse]
# 전체 차수는 7개인데, boolean 차원은 3개여서 errror 발생 

IndexError: ignored

In [55]:
myTrueFalse = [True, False, True, False, True, False, True]

In [56]:
arr[myTrueFalse]

array([1, 3, 5, 7])

### 3-2. 조건필터

조건 연산자를 활용하여 필터를 생성할 수 있습니다

In [58]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
arr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

필터를 활용하여 필터에 True 조건만 색인 합니다.

이럴 때 꺾쇠 괄호로 한 번 더 묶어만 주면 됩니다. (꺾쇠 괄호 안에 조건문 삽입) 

arr2d[**조건필터**]

In [59]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [60]:
arr2d[ arr2d > 2 ]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
arr2d[ arr2d < 5 ]

array([1, 2, 3, 4])