In [1]:
import numpy as np

## 1. arange란?

### array + range => arange

### 1-1. 순서대로 리스트에 값을 생성하려면?

1~10까지 값을 생성하려면?

In [2]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
def myGen(start=1, stop=10, step=1):
    myList = [ ]
    
    for i in range(start, stop, step):
        myList.append(i)
        
    return myList

result = myGen(0,5)
result


[0, 1, 2, 3, 4]

In [5]:
result = myGen(stop=5, start=2)
result

[2, 3, 4]

### 1-2. arange를 사용해서 쉽게 생성하기

첫번째 인자에는 **start 이상**, 두번째 인자에는 **stop의 미만** 이 들어갑니다. (option 세번째 인자 step) 

In [6]:
arr = np.arange(1, 11)

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
type(arr)

numpy.ndarray

## 1-3. keyword 인자를 사용해보기

keyword 인자는 파라미터(인자)의 keyword를 지정해줌으로썬 순서 없이 지정해 줄 수 있습니다.

In [9]:
arr = np.arange(start=1, stop=11)

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.arange(stop=11, start=1)

In [12]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 1-4. 홀수의 값만 생성

1~10 사이의 값중 홀수만 생성해 보세요.

**step 키워드 활용**

### (start, stop, step)

In [13]:
arr = np.arange(1, 11, 1)

In [14]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr = np.arange(start=1, stop=11, step=2)

In [ ]:
arr

array([1, 3, 5, 7, 9])

## 2. range (numpy와는 상관없는 python 문법)

* range는 말 그대로 범위를 지정해 주는 것입니다.
* np.arange와 헷갈리시는 분들이 많아 이번 시간에 같이 다룹니다.
* 보통 for in 의 반복문에서 많이 사용됩니다.

In [16]:
arr = np.arange(1, 11)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


### 2-1. range 구문 활용시

In [19]:
test= range(1, 11)
print(test)
print(type(test))

range(1, 11)
<class 'range'>


In [20]:
# range메소드는 range만으로 실행되는 것이 아니라 for문과 같이 반복문을 만났을때 실행
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [21]:
for i in range(1, 11, 2):
    print(i)

1
3
5
7
9


In [ ]:
import numpy as np
a = 3
b = 4
#c = a*b
c = np.dot(a,b)
c

12