In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.6


## 1. 1차원 정렬

1차원 정렬은 매우 간단합니다.

In [3]:
import numpy as np
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [4]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

np.sort(arr)

In [5]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [6]:
# 순정렬 
np.sort(arr)[::1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

기본적으로 오름차순 정렬을 수행합니다.

In [7]:
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

내림차순 정렬은 옵션에 -1 값을 주면됩니다.

하지만, 이 값들은 **유지가 되지 않습니다**!

값을 sort 된 상태로 저장하려면, 배열 자체에 sort를 해줄 수 있습니다.

In [8]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [9]:
arr2 = np.sort(arr)

In [10]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [11]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [12]:
arr.sort()

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

## 2. N차원 정렬

In [14]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])

In [15]:
arr2d.shape

(3, 4)

In [16]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

### 2-1. 열 정렬 (왼쪽에서 오른쪽으로)

In [17]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [18]:
np.sort(arr2d, axis=1) # 열기준(서로 다른 열기리), 가로방향

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

### 2-2. 행 정렬 (위에서 아래로)

In [19]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [20]:
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

## 3. index를 반환하는 argsort

정렬된 값을 반환하는 것이 아닌 index를 반환합니다.

In [21]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])


### 3-1. 열 정렬 (왼쪽에서 오른쪽으로)

In [22]:
np.argsort(arr2d, axis=1)  # 서로 다른 열끼리, 같은 행끼리 비교 (가로방향)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

### 3-2. 행 정렬

In [23]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [24]:
np.sort(arr2d, axis=0)  # 서로 다른 행끼리, 같은 열끼리 비교 (세로방향)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [25]:
np.argsort(arr2d, axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])

In [26]:
name = np.array(['쯔위','수지','카즈하','진욱'])
score = np.array([95,97,100,99])
np.argsort(name) 

array([1, 3, 0, 2])

In [27]:
np.argsort(score)

array([0, 1, 3, 2])

In [28]:
score_index = np.argsort(score)[::-1] # 내림차순 정렬
score_index

array([2, 3, 1, 0])

In [29]:
name[score_index]  # 성적 순 정렬 

array(['카즈하', '진욱', '수지', '쯔위'], dtype='<U3')