In [1]:
import numpy as np

## 1. 행렬 - 덧셈

### 1-1. 덧셈

In [2]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [3]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [4]:
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [5]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [6]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [8]:
# a + b
# ValueError 발생

### 1-2. Sum

In [9]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [10]:
np.sum(a, axis=0) # 행 끼리, 서로 다른 행끼리(세로방향)

array([3, 5, 7])

In [11]:
np.sum(a, axis=1) # 열 끼리, 서로 다른 열끼리(가로방향)

array([6, 9])

## 2. 행렬 - 뺄셈

In [12]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [13]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [14]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [15]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [16]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [18]:
# a - b
# ValueError 발생

## 3. 곱셈

일반 곱셈

In [19]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [20]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [21]:
a.shape, b.shape

((2, 3), (2, 3))

In [22]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

단순 곱셈과 dot product는 다릅니다. 이점 유의하세요!

In [23]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [24]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [25]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [27]:
# a * b
# ValueError 

## 행렬곱연산

In [28]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [29]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [30]:
a.shape, b.shape

((3, 3), (3, 2))

In [31]:
# 행렬곱을 할때 dot메소드 사용
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [32]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])